name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.7gveZJvBaKTknYKeii373Y4L }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_EID4nP2mFloFs1Yk12ibVM45WGEr }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.XlxNWv2CVIUEo8ab1RTZQ4ka }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.XlxNWv2CVIUEo8ab1RTZQ4ka }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.XlxNWv2CVIUEo8ab1RTZQ4ka }}
